import { ArrowRight, Building2, GraduationCap, Menu, PencilRuler, Plane, UsersRound } from 'lucide-react'
import Image from 'next/image'
import Link from 'next/link'
import { programs, schools, services, siteConfig } from '@/data/site'

function Brand() { return <Link className="brand" href="/"><Image className="brand-image" src="/images/logo-main.jpg" alt="MISOLA 米岛时尚设计留学" width={1600} height={900} priority /></Link> }
const icons = [GraduationCap, PencilRuler, Building2, Plane, UsersRound]

export default function Home() {
  const jsonLd = { '@context': 'https://schema.org', '@type': 'EducationalOrganization', name: siteConfig.name, url: siteConfig.url, description: siteConfig.description, areaServed: 'CN', knowsAbout: ['Italian Fashion Design', 'Fashion Education'] }
  return <div className="site" id="top">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
    <header className="header shell"><Brand /><nav className="nav"><Link className="active" href="/">首页</Link><Link href="/#about">关于米岛</Link><Link href="/schools">热门院校</Link><Link href="/services">留学服务</Link><Link href="/#programs">专业推荐</Link><Link href="/#cases">成功案例</Link><Link href="/contact">免费咨询</Link></nav><div className="header-actions"><Link className="outline-button" href="/contact">预约咨询 <ArrowRight size={14} /></Link><button className="menu-button" aria-label="打开菜单"><Menu size={22} /></button></div></header>
    <main>
      <section className="hero shell" id="about"><div className="hero-copy"><p className="eyebrow">MISOLA / ITALIAN FASHION DESIGN</p><h1 className="hero-wordmark" aria-label="MISOLA" /><h2>米岛时尚设计留学</h2><div className="rule" /><p className="hero-desc">专注意大利时尚留学<br /><span>设计 · 时尚 · 未来</span></p><Link className="solid-button" href="/services">探索更多 <ArrowRight size={16} /></Link></div><div className="hero-art"><span className="art-caption">MILANO / ITALIA<br /><b>Design the future.</b></span></div></section>
      <section className="section shell" id="services"><div className="section-heading"><div><p className="eyebrow">WHAT WE DO</p><h2>我们的服务</h2></div><p>全方位时尚设计留学服务，助你实现世界名校梦想。</p></div><div className="service-grid">{services.map(({ title, text, image }, index) => { const Icon = icons[index]; return <article className={`service-card service-${index + 1}`} style={{ backgroundImage: `linear-gradient(155deg, rgba(8,8,8,.18), rgba(8,8,8,.88)), url(${image})` }} key={title}><div className="card-icon"><Icon size={20} strokeWidth={1.5} /></div><h3>{title}</h3><p>{text}</p><span className="card-number">0{index + 1}</span></article> })}</div></section>
      <section className="school-band" id="portfolio"><div className="shell"><div className="section-heading school-heading"><div><p className="eyebrow">ITALIAN SCHOOL DIRECTORY</p><h2>意大利热门院校</h2></div><Link href="/schools" className="text-link">查看全部院校 <ArrowRight size={16} /></Link></div><div className="school-grid">{schools.map(school => <Link className="school" href={`/schools/${school.slug}`} key={school.slug}><div className="school-visual"><Image className="school-photo" src={school.image} alt={`${school.cn} 校园与设计环境`} width={900} height={540} /><div className="school-logo-frame"><Image className="school-logo" src={school.logo} alt={`${school.name} logo`} width={768} height={315} /></div></div><div><strong>{school.name}</strong><span>{school.cn}</span></div></Link>)}</div></div></section>
      <section className="program-band shell" id="programs"><div className="section-heading"><div><p className="eyebrow">PROGRAM RECOMMENDATIONS</p><h2>专业推荐</h2></div><p>从服装设计到时尚商业，探索适合你的意大利专业方向。</p></div><div className="program-grid">{programs.map(program => <Link className="program-card" href={`/programs/${program.slug}`} key={program.slug}><Image src={program.image} alt={`${program.title} ${program.english}`} width={900} height={540} /><div className="program-card-body"><span>{program.category}</span><h3>{program.title}</h3><p>{program.english}</p><ArrowRight size={17} /></div></Link>)}</div></section>
      <section className="cases shell" id="cases"><div className="case-intro"><p className="eyebrow">SELECTED CASES</p><h2>成功案例</h2><p>案例内容与学生信息将在后续持续更新。</p></div><div className="case-stack">{['案例一','案例二','案例三','案例四'].map((name, index) => <article key={name}><div className={`case-image case-${index + 1}`}><span>{name}<br />CONTENT TO COME</span></div><p>案例内容待补充<br /><small>Fashion / Design</small></p></article>)}</div></section>
      <section className="contact-strip shell" id="events"><p className="eyebrow">START YOUR JOURNEY</p><h2>让你的设计，被世界看见。</h2><Link className="solid-button" href="/contact">预约免费咨询 <ArrowRight size={16} /></Link></section>
    </main>
<footer className="footer shell"><Brand /><div className="footer-contact"><span>☎　联系方式待填写</span><span>✉　邮箱待填写</span><span>⌖　地址待填写</span></div><div className="wechat-placeholder" aria-label="微信二维码待上传"><span>微信二维码</span><small>二维码待上传</small></div><div className="footer-bottom">© 2026 MISOLA 米岛时尚设计留学　All Rights Reserved.</div></footer>
  </div>
}
